name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Generate Android Package (PWABuilder)
      uses: pwabuilder/pwabuilder-androidpackageName@v2
      with:
        url: 'https://ticbull-academy.vercel.app'
        name: 'TicBull Academy'
        manifestUrl: 'https://ticbull-academy.vercel.app/manifest.json'

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TicBull-Academy-Official-App
        path: |
          output/*.apk
          output/*.aab
